/* ============================================================
   Jab — data layer
   Fighter profiles, rankings, schedules, promoters and news.

   Rankings: The Ring Magazine pound-for-pound Top 10 (boxing) and
   the official UFC men's pound-for-pound Top 15 (MMA). Records, titles,
   fight histories and portraits gathered late June 2026 from Wikipedia
   and other sources (ESPN, The Ring, UFC, CBS, DAZN, BoxingScene).
   Portraits are freely-licensed Wikimedia Commons images. Each profile
   links to the fighter's full verified record. Some upcoming bouts are
   targeted matchups rather than signed contracts.
   ============================================================ */

const PROMOTERS = [
  { id: "top-rank", name: "Top Rank", sport: "boxing", founded: 1973, head: "Bob Arum", hq: "Las Vegas, Nevada, USA", site: "https://www.toprank.com", logo: "https://en.wikipedia.org/wiki/Special:FilePath/Top%20Rank%20logo.png?width=160",
    description: "One of boxing's most storied promoters, Top Rank has guided dozens of world champions since 1973 and broadcasts marquee cards on ESPN." },
  { id: "matchroom", name: "Matchroom Boxing", sport: "boxing", founded: 1987, head: "Eddie Hearn", hq: "Brentwood, Essex, UK", site: "https://www.matchroomboxing.com", logo: "https://en.wikipedia.org/wiki/Special:FilePath/Matchroom%20logo.jpeg?width=160",
    description: "Led by Eddie Hearn, Matchroom stages major events across the UK, US and Middle East and partners with DAZN for global streaming." },
  { id: "pbc", name: "Premier Boxing Champions", sport: "boxing", founded: 2015, head: "Al Haymon", hq: "Los Angeles, California, USA", site: "https://www.premierboxingchampions.com", logo: "https://www.premierboxingchampions.com/sites/all/themes/haymon/images/global/favicon-144x144.png",
    description: "Founded by manager-promoter Al Haymon, PBC delivers premium pay-per-view and Prime Video cards featuring many of America's biggest stars." },
  { id: "golden-boy", name: "Golden Boy Promotions", sport: "boxing", founded: 2002, head: "Oscar De La Hoya", hq: "Los Angeles, California, USA", site: "https://www.goldenboy.com", logo: "https://en.wikipedia.org/wiki/Special:FilePath/Golden%20Boy%20Promotions.gif?width=160",
    description: "Started by six-division champion Oscar De La Hoya, Golden Boy develops rising talent and stages a deep slate of fan-favorite cards." },
  { id: "ohashi", name: "Ohashi Boxing (Japan)", sport: "boxing", founded: 2004, head: "Hideyuki Ohashi", hq: "Yokohama, Japan", site: "https://www.ohashi-boxing.jp",
    description: "The Yokohama gym run by former world champion Hideyuki Ohashi, home to Japan's elite and the team behind Naoya Inoue." },
  { id: "ufc", name: "UFC", sport: "mma", founded: 1993, head: "Dana White (President)", hq: "Las Vegas, Nevada, USA", site: "https://www.ufc.com", logo: "https://en.wikipedia.org/wiki/Special:FilePath/UFC%20Logo.svg?width=160",
    description: "The Ultimate Fighting Championship is the world's premier mixed martial arts organization, owned by TKO Group, staging events globally and on ESPN/PPV." },
];

const IMG = "https://upload.wikimedia.org/wikipedia/commons/thumb/";

const FIGHTERS = [
  /* ===================== BOXING — THE RING P4P TOP 10 ===================== */
  {
    id: "naoya-inoue", name: "Naoya Inoue", nickname: "Monster", sport: "boxing", flag: "🇯🇵", nationality: "Japan", division: "Super Bantamweight",
    record: { w: 33, l: 0, d: 0, ko: 27 }, methods: { ko: 27, dec: 6 }, ringRank: 1,
    image: IMG + "4/49/Naoya_Inoue_20230302suports_03.jpg/512px-Naoya_Inoue_20230302suports_03.jpg",
    recordUrl: "https://en.wikipedia.org/wiki/Naoya_Inoue",
    stance: "Orthodox", height: `5'5" (165 cm)`, reach: `67.5" (171 cm)`, age: 33, dob: "1993-04-10", hometown: "Zama, Kanagawa, Japan", debut: 2012, promoterId: "ohashi",
    currentTitles: ["Undisputed Super Bantamweight Champion (WBA, WBC, IBF, WBO)", "The Ring Super Bantamweight Champion"], standing: "",
    bio: "Widely rated the No. 1 pound-for-pound boxer on the planet, the 'Monster' is the undisputed super bantamweight champion and a former undisputed bantamweight king. In May 2026 he outpointed Junto Nakatani in the biggest fight in Japanese boxing history.",
    social: { instagram: "https://instagram.com/naoyainoue_410", x: "https://x.com/naoyainoue_410" },
    upcoming: [{ date: "2027-01-24", opponent: "Jesse 'Bam' Rodriguez", event: "Undisputed Superfight (targeted)", venue: "Tokyo, Japan", title: "Super Bantamweight" }],
    recent: [
      { date: "2026-05-02", opponent: "Junto Nakatani", result: "W", method: "UD", round: 12, event: "Tokyo Dome, Tokyo" },
      { date: "2025-12-27", opponent: "David Picasso", result: "W", method: "UD", round: 12, event: "Riyadh, Saudi Arabia" },
      { date: "2025-09-14", opponent: "Murodjon Akhmadaliev", result: "W", method: "UD", round: 12, event: "IG Arena, Nagoya" },
      { date: "2025-05-04", opponent: "Ramon Cardenas", result: "W", method: "TKO", round: 8, event: "T-Mobile Arena, Las Vegas" },
      { date: "2025-01-24", opponent: "Kim Ye-joon", result: "W", method: "KO", round: 4, event: "Ariake Arena, Tokyo" },
      { date: "2024-09-03", opponent: "TJ Doheny", result: "W", method: "TKO", round: 7, event: "Ariake Arena, Tokyo" },
      { date: "2024-05-06", opponent: "Luis Nery", result: "W", method: "KO", round: 6, event: "Tokyo Dome, Tokyo" },
      { date: "2023-12-26", opponent: "Marlon Tapales", result: "W", method: "KO", round: 10, event: "Ariake Arena, Tokyo" },
      { date: "2023-07-25", opponent: "Stephen Fulton", result: "W", method: "TKO", round: 8, event: "Ariake Arena, Tokyo" },
      { date: "2022-12-13", opponent: "Paul Butler", result: "W", method: "KO", round: 11, event: "Ariake Arena, Tokyo" },
      { date: "2022-06-07", opponent: "Nonito Donaire", result: "W", method: "TKO", round: 2, event: "Saitama Super Arena" },
      { date: "2021-12-14", opponent: "Aran Dipaen", result: "W", method: "TKO", round: 8, event: "Ryōgoku Kokugikan, Tokyo" },
    ],
    news: [
      { t: "Inoue outpoints Nakatani in historic Tokyo Dome superfight", s: "ESPN", d: "2026-05-02", u: "https://www.espn.com/boxing/story/_/id/47426170/naoya-inoue-junto-nakatani-win-set-2026-megafight" },
      { t: "Analyzing Inoue's updated 33-0 professional record", s: "Boxing News & Views", d: "2026-05-05", u: "https://www.boxingnewsandviews.com/2026/05/05/analyzing-the-updated-naoya-inoue-professional-boxing-record/" },
      { t: "Naoya Inoue — official fighter profile & ratings", s: "The Ring", d: "2026-05-04", u: "https://www.ringmagazine.com/fighters/naoya-inoue-3EiWl7niEWkAd2sT8cfQec" },
    ],
  },
  {
    id: "oleksandr-usyk", name: "Oleksandr Usyk", nickname: "The Cat", sport: "boxing", flag: "🇺🇦", nationality: "Ukraine", division: "Heavyweight",
    record: { w: 24, l: 0, d: 0, ko: 15 }, methods: { ko: 15, dec: 9 }, ringRank: 2,
    image: IMG + "2/2f/2022_-_Centre_Stage_EN1_4500_%2852471602047%29_%28cropped%29.jpg/512px-2022_-_Centre_Stage_EN1_4500_%2852471602047%29_%28cropped%29.jpg",
    recordUrl: "https://en.wikipedia.org/wiki/Oleksandr_Usyk",
    stance: "Southpaw", height: `6'3" (191 cm)`, reach: `78" (198 cm)`, age: 39, dob: "1987-01-17", hometown: "Simferopol, Crimea, Ukraine", debut: 2013, promoterId: "matchroom",
    currentTitles: ["WBA, WBC & IBF Heavyweight Champion", "The Ring Heavyweight Champion"], standing: "",
    bio: "A masterful southpaw technician and Olympic gold medalist who became undisputed champion at both cruiserweight and heavyweight. He vacated the WBO belt in late 2025 but remains the lineal Ring champion, stopping Rico Verhoeven in May 2026.",
    social: { instagram: "https://instagram.com/usykaa", x: "https://x.com/usykaa" },
    upcoming: [{ date: "2026-09-27", opponent: "Agit Kabayel", event: "Mandatory Title Defense (purse bid pending)", venue: "Riyadh, Saudi Arabia", title: "Heavyweight" }],
    recent: [
      { date: "2026-05-23", opponent: "Rico Verhoeven", result: "W", method: "TKO", round: 11, event: "Giza, Egypt" },
      { date: "2025-07-19", opponent: "Daniel Dubois", result: "W", method: "KO", round: 5, event: "Wembley Stadium, London" },
      { date: "2024-12-21", opponent: "Tyson Fury", result: "W", method: "UD", round: 12, event: "Kingdom Arena, Riyadh" },
      { date: "2024-05-18", opponent: "Tyson Fury", result: "W", method: "SD", round: 12, event: "Kingdom Arena, Riyadh" },
      { date: "2023-08-26", opponent: "Daniel Dubois", result: "W", method: "TKO", round: 9, event: "Tarczyński Arena, Wrocław" },
      { date: "2022-08-20", opponent: "Anthony Joshua", result: "W", method: "SD", round: 12, event: "Jeddah, Saudi Arabia" },
      { date: "2021-09-25", opponent: "Anthony Joshua", result: "W", method: "UD", round: 12, event: "Tottenham Stadium, London" },
      { date: "2020-10-31", opponent: "Derek Chisora", result: "W", method: "UD", round: 12, event: "Wembley Arena, London" },
      { date: "2019-10-12", opponent: "Chazz Witherspoon", result: "W", method: "RTD", round: 7, event: "Wintrust Arena, Chicago" },
      { date: "2018-11-10", opponent: "Tony Bellew", result: "W", method: "KO", round: 8, event: "Manchester Arena, England" },
      { date: "2018-07-21", opponent: "Murat Gassiev", result: "W", method: "UD", round: 12, event: "Olimpiyskiy, Moscow" },
      { date: "2018-01-27", opponent: "Mairis Briedis", result: "W", method: "MD", round: 12, event: "Arena Riga, Latvia" },
    ],
    news: [
      { t: "Usyk stops Rico Verhoeven in the 11th to retain heavyweight crown", s: "FIGHTMAG", d: "2026-05-23", u: "https://www.fightmag.com/boxing-oleksandr-usyk-vs-rico-verhoeven-live-results/" },
      { t: "Deadline looms for Usyk–Kabayel mandatory negotiations", s: "BoxingScene", d: "2026-06-22", u: "https://www.boxingscene.com/articles/deadline-looms-for-usyk-and-kabayel-camps-to-reach-fight-agreement-independently" },
      { t: "Oleksandr Usyk — career record and titles", s: "Wikipedia", d: "2026-06-01", u: "https://en.wikipedia.org/wiki/Oleksandr_Usyk" },
    ],
  },
  {
    id: "jesse-rodriguez", name: "Jesse Rodriguez", nickname: "Bam", sport: "boxing", flag: "🇺🇸", nationality: "USA", division: "Bantamweight",
    record: { w: 24, l: 0, d: 0, ko: 17 }, methods: { ko: 17, dec: 7 }, ringRank: 3,
    image: "https://images.ctfassets.net/lg76kxmf55ue/3HdsSOJy1d7GU3td8EvV1w/d6173ae84aa8ba12e12038c5e5af3cf1/JesseRodriguez.png?w=600&h=750&fit=fill&f=face&fm=jpg&q=80",
    recordUrl: "https://en.wikipedia.org/wiki/Jesse_Rodriguez_(boxer)",
    stance: "Southpaw", height: `5'5" (165 cm)`, reach: `65" (165 cm)`, age: 26, dob: "2000-02-04", hometown: "San Antonio, Texas, USA", debut: 2017, promoterId: "matchroom",
    currentTitles: ["WBA Bantamweight Champion"], standing: "",
    bio: "A slick switch-hitting prodigy out of San Antonio, 'Bam' became a three-division champion before turning 27. In June 2026 he vacated his unified super flyweight titles to move up and knock out Antonio Vargas for the WBA bantamweight belt.",
    social: { instagram: "https://instagram.com/bamrodriguez_", x: "https://x.com/bamrodriguez22" },
    upcoming: [{ date: "2026-10-17", opponent: "Christian Medina", event: "Bantamweight Unification (targeted)", venue: "San Antonio, Texas", title: "Bantamweight" }],
    recent: [
      { date: "2026-06-13", opponent: "Antonio Vargas", result: "W", method: "KO", round: 6, event: "Desert Diamond Arena, Glendale" },
      { date: "2025-11-22", opponent: "Fernando Martínez", result: "W", method: "KO", round: 10, event: "Kingdom Arena, Riyadh" },
      { date: "2025-07-19", opponent: "Phumelele Cafu", result: "W", method: "TKO", round: 10, event: "Ford Center, Frisco" },
      { date: "2024-11-09", opponent: "Pedro Guevara", result: "W", method: "TKO", round: 3, event: "Wells Fargo Center, Philadelphia" },
      { date: "2024-06-29", opponent: "Juan Francisco Estrada", result: "W", method: "KO", round: 7, event: "Footprint Center, Phoenix" },
      { date: "2023-12-16", opponent: "Sunny Edwards", result: "W", method: "RTD", round: 9, event: "Desert Diamond Arena, Glendale" },
      { date: "2023-04-08", opponent: "Cristian Gonzalez", result: "W", method: "UD", round: 12, event: "Techport Arena, San Antonio" },
      { date: "2022-09-17", opponent: "Israel González", result: "W", method: "UD", round: 12, event: "T-Mobile Arena, Las Vegas" },
      { date: "2022-06-25", opponent: "Srisaket Sor Rungvisai", result: "W", method: "TKO", round: 8, event: "Tech Port Arena, San Antonio" },
      { date: "2022-02-05", opponent: "Carlos Cuadras", result: "W", method: "UD", round: 12, event: "Footprint Center, Phoenix" },
      { date: "2021-10-16", opponent: "Jose Alejandro Burgos", result: "W", method: "KO", round: 4, event: "Chukchansi Park, Fresno" },
      { date: "2020-12-12", opponent: "Saúl Juárez", result: "W", method: "KO", round: 2, event: "MGM Grand, Las Vegas" },
    ],
    news: [
      { t: "Bam Rodriguez stops Antonio Vargas to win WBA bantamweight title", s: "Yahoo Sports", d: "2026-06-13", u: "https://sports.yahoo.com/boxing/live/bam-rodriguez-vs-antonio-vargas-live-now-results-round-by-round-updates-ring-walks-for-tonights-fight-060000739.html" },
      { t: "Rodriguez vacates super flyweight belts for bantamweight move", s: "Boxing News Online", d: "2026-06-05", u: "https://boxingnewsonline.net/news/jesse-rodriguez-vacates-world-titles/" },
      { t: "From overlooked prospect to P4P star: the rise of 'Bam'", s: "ESPN", d: "2026-05-20", u: "https://www.espn.com/boxing/story/_/id/49029877/from-overlooked-boxing-prospect-p4p-star-rise-jesse-bam%C2%A0rodriguez" },
    ],
  },
  {
    id: "dmitry-bivol", name: "Dmitry Bivol", nickname: "", sport: "boxing", flag: "🇰🇬", nationality: "Kyrgyzstan", division: "Light Heavyweight",
    record: { w: 25, l: 1, d: 0, ko: 12 }, methods: { ko: 12, dec: 13 }, ringRank: 8,
    image: IMG + "c/c5/Dmitry_Bivol_in_2023.jpg/512px-Dmitry_Bivol_in_2023.jpg",
    recordUrl: "https://en.wikipedia.org/wiki/Dmitry_Bivol",
    stance: "Orthodox", height: `6'0" (183 cm)`, reach: `72" (183 cm)`, age: 35, dob: "1990-12-18", hometown: "Tokmok, Kyrgyzstan", debut: 2014, promoterId: "matchroom",
    currentTitles: ["WBA, IBF & WBO Light Heavyweight Champion", "The Ring Light Heavyweight Champion"], standing: "",
    bio: "A precision boxer with an airtight defense, Bivol famously beat Canelo Álvarez before twice trading with Artur Beterbiev. He shut out Michael Eifert in a May 2026 homecoming to retain his unified light heavyweight crown.",
    social: { instagram: "https://instagram.com/bivol_d", x: "https://x.com/bivol_d" },
    upcoming: [{ date: "2026-12-12", opponent: "Artur Beterbiev", event: "Light Heavyweight Trilogy (targeted)", venue: "Riyadh, Saudi Arabia", title: "Light Heavyweight" }],
    recent: [
      { date: "2026-05-30", opponent: "Michael Eifert", result: "W", method: "UD", round: 12, event: "UMMC Arena, Yekaterinburg" },
      { date: "2025-02-22", opponent: "Artur Beterbiev", result: "W", method: "MD", round: 12, event: "The Venue, Riyadh" },
      { date: "2024-10-12", opponent: "Artur Beterbiev", result: "L", method: "MD", round: 12, event: "Kingdom Arena, Riyadh" },
      { date: "2024-06-01", opponent: "Malik Zinad", result: "W", method: "TKO", round: 6, event: "Kingdom Arena, Riyadh" },
      { date: "2023-12-23", opponent: "Lyndon Arthur", result: "W", method: "UD", round: 12, event: "Kingdom Arena, Riyadh" },
      { date: "2022-11-05", opponent: "Gilberto Ramírez", result: "W", method: "UD", round: 12, event: "Etihad Arena, Abu Dhabi" },
      { date: "2022-05-07", opponent: "Canelo Álvarez", result: "W", method: "UD", round: 12, event: "T-Mobile Arena, Las Vegas" },
      { date: "2021-12-11", opponent: "Umar Salamov", result: "W", method: "UD", round: 12, event: "KRK Uralets, Ekaterinburg" },
      { date: "2021-05-01", opponent: "Craig Richards", result: "W", method: "UD", round: 12, event: "AO Arena, Manchester" },
      { date: "2019-10-12", opponent: "Lenin Castillo", result: "W", method: "UD", round: 12, event: "Wintrust Arena, Chicago" },
      { date: "2019-03-09", opponent: "Joe Smith Jr.", result: "W", method: "UD", round: 12, event: "Turning Stone, Verona NY" },
      { date: "2018-11-24", opponent: "Jean Pascal", result: "W", method: "UD", round: 12, event: "Hard Rock, Atlantic City" },
    ],
    news: [
      { t: "Bivol shuts out Michael Eifert to retain unified LHW titles", s: "Bad Left Hook", d: "2026-05-30", u: "https://www.badlefthook.com/boxing-results/115973/dmitry-bivol-shuts-out-michael-eifert-in-return-what-comes-next-boxing-news-2026" },
      { t: "Bivol targets a major legacy fight to close out 2026", s: "The Ring", d: "2026-04-15", u: "https://www.ringmagazine.com/news/manager-dmitry-bivol-targets-spring-return-before-major-fight-later-in-2026-3cfONvD9VunqJTHWJujmp2" },
      { t: "Dmitry Bivol — record and title history", s: "Wikipedia", d: "2026-06-01", u: "https://en.wikipedia.org/wiki/Dmitry_Bivol" },
    ],
  },
  {
    id: "artur-beterbiev", name: "Artur Beterbiev", nickname: "", sport: "boxing", flag: "🇨🇦", nationality: "Canada / Russia", division: "Light Heavyweight",
    record: { w: 21, l: 1, d: 0, ko: 20 }, methods: { ko: 20, dec: 1 }, ringRank: 9,
    image: IMG + "6/64/Artur_Beterbiev%2C_December_2019.jpg/512px-Artur_Beterbiev%2C_December_2019.jpg",
    recordUrl: "https://en.wikipedia.org/wiki/Artur_Beterbiev",
    stance: "Orthodox", height: `6'1" (185 cm)`, reach: `72" (183 cm)`, age: 41, dob: "1985-01-21", hometown: "Khasavyurt, Dagestan, Russia", debut: 2013, promoterId: "top-rank",
    currentTitles: [], standing: "Former Undisputed Light Heavyweight Champion",
    bio: "The most feared puncher of his era, Beterbiev knocked out the first 20 opponents of his pro career. A two-time Olympian, he lost his undisputed crown to Dmitry Bivol in their February 2025 rematch and is chasing a trilogy decider at 41.",
    social: { instagram: "https://instagram.com/arturbeterbiev", x: "https://x.com/beterbievofficial" },
    upcoming: [],
    recent: [
      { date: "2025-02-22", opponent: "Dmitry Bivol", result: "L", method: "MD", round: 12, event: "The Venue, Riyadh" },
      { date: "2024-10-12", opponent: "Dmitry Bivol", result: "W", method: "MD", round: 12, event: "Kingdom Arena, Riyadh" },
      { date: "2024-01-13", opponent: "Callum Smith", result: "W", method: "TKO", round: 7, event: "Videotron Centre, Quebec City" },
      { date: "2023-01-28", opponent: "Anthony Yarde", result: "W", method: "TKO", round: 8, event: "OVO Arena Wembley, London" },
      { date: "2022-06-18", opponent: "Joe Smith Jr.", result: "W", method: "TKO", round: 2, event: "Hulu Theater, New York" },
      { date: "2021-12-17", opponent: "Marcus Browne", result: "W", method: "KO", round: 9, event: "Bell Centre, Montreal" },
      { date: "2021-03-20", opponent: "Adam Deines", result: "W", method: "TKO", round: 10, event: "Khodynka Ice Palace, Moscow" },
      { date: "2019-10-18", opponent: "Oleksandr Gvozdyk", result: "W", method: "TKO", round: 10, event: "Liacouras Center, Philadelphia" },
      { date: "2019-05-04", opponent: "Radivoje Kalajdzic", result: "W", method: "KO", round: 5, event: "Stockton Arena, California" },
      { date: "2018-10-06", opponent: "Callum Johnson", result: "W", method: "KO", round: 4, event: "Wintrust Arena, Chicago" },
      { date: "2017-11-11", opponent: "Enrico Kölling", result: "W", method: "KO", round: 12, event: "Save Mart Arena, Fresno" },
      { date: "2016-12-23", opponent: "Isidro Ranoni Prieto", result: "W", method: "TKO", round: 1, event: "Casino du Lac-Leamy, Gatineau" },
    ],
    news: [
      { t: "Beterbiev prioritizes a Bivol trilogy over a Benavidez clash", s: "No Smoke Boxing", d: "2026-06-22", u: "https://nosmokeboxing.com/artur-beterbiev-prioritizes-dmitry-bivol-trilogy-over-david/" },
      { t: "At 41, Beterbiev says he's only chasing big fights now", s: "Boxing News & Views", d: "2026-06-24", u: "https://www.boxingnewsandviews.com/2026/06/24/artur-beterbiev-looks-to-be-going-after-only-big-fights-now/" },
      { t: "Best fights to make in 2026: Beterbiev–Benavidez", s: "DAZN", d: "2026-01-10", u: "https://www.dazn.com/en-US/news/boxing/best-fights-to-be-made-in-2026-beterbiev-benavidez-smith-azim-fury-joshua/48i5rqy3ee811fyrxw7yy61cq" },
    ],
  },
  {
    id: "junto-nakatani", name: "Junto Nakatani", nickname: "Big Bang", sport: "boxing", flag: "🇯🇵", nationality: "Japan", division: "Super Bantamweight",
    record: { w: 32, l: 1, d: 0, ko: 24 }, methods: { ko: 24, dec: 8 }, ringRank: 7,
    image: "https://images.ctfassets.net/lg76kxmf55ue/3RlBVTYMHnyqDQUM8jqGFH/041dd401e4c6e996c94bca91cc62b0d5/JuntoNakatani.png?w=600&h=750&fit=fill&f=face&fm=jpg&q=80",
    recordUrl: "https://en.wikipedia.org/wiki/Junto_Nakatani",
    stance: "Southpaw", height: `5'7" (170 cm)`, reach: `68" (173 cm)`, age: 28, dob: "1997-11-29", hometown: "Tokyo, Japan", debut: 2015, promoterId: "top-rank",
    currentTitles: [], standing: "Former Three-Division World Champion",
    bio: "A towering, hard-hitting southpaw and former three-division champion, Nakatani vacated his bantamweight titles to chase Naoya Inoue. He suffered the first loss of his career to the 'Monster' in their May 2026 Tokyo Dome megafight.",
    social: { instagram: "https://instagram.com/junto_nakatani", x: "https://x.com/junto_nakatani" },
    upcoming: [],
    recent: [
      { date: "2026-05-02", opponent: "Naoya Inoue", result: "L", method: "UD", round: 12, event: "Tokyo Dome, Tokyo" },
      { date: "2025-12-27", opponent: "Sebastian Hernandez", result: "W", method: "UD", round: 12, event: "Riyadh, Saudi Arabia" },
      { date: "2025-06-08", opponent: "Ryosuke Nishida", result: "W", method: "RTD", round: 6, event: "Ariake Colosseum, Tokyo" },
      { date: "2025-02-24", opponent: "David Cuellar Contreras", result: "W", method: "KO", round: 3, event: "Ariake Arena, Tokyo" },
      { date: "2024-10-14", opponent: "Petch Sor Chitpattana", result: "W", method: "TKO", round: 6, event: "Ariake Arena, Tokyo" },
      { date: "2024-07-20", opponent: "Vincent Astrolabio", result: "W", method: "KO", round: 1, event: "Ryōgoku Kokugikan, Tokyo" },
      { date: "2024-02-24", opponent: "Alexandro Santiago", result: "W", method: "TKO", round: 6, event: "Ryōgoku Kokugikan, Tokyo" },
      { date: "2023-09-18", opponent: "Argi Cortes", result: "W", method: "UD", round: 12, event: "Ariake Arena, Tokyo" },
      { date: "2023-05-20", opponent: "Andrew Moloney", result: "W", method: "KO", round: 12, event: "MGM Grand, Las Vegas" },
      { date: "2022-11-01", opponent: "Francisco Rodríguez Jr.", result: "W", method: "UD", round: 10, event: "Super Arena, Saitama" },
    ],
    news: [
      { t: "Nakatani falls to Inoue in 'biggest fight in Japanese history'", s: "ESPN", d: "2026-05-02", u: "https://www.espn.com/boxing/story/_/id/47426170/naoya-inoue-junto-nakatani-win-set-2026-megafight" },
      { t: "Junto Nakatani — record, titles and career", s: "Wikipedia", d: "2026-06-01", u: "https://en.wikipedia.org/wiki/Junto_Nakatani" },
      { t: "Nakatani news, record & next fight", s: "box.live", d: "2026-05-10", u: "https://box.live/boxers/junto-nakatani/" },
    ],
  },
  {
    id: "shakur-stevenson", name: "Shakur Stevenson", nickname: "", sport: "boxing", flag: "🇺🇸", nationality: "USA", division: "Super Lightweight",
    record: { w: 25, l: 0, d: 0, ko: 11 }, methods: { ko: 11, dec: 14 }, ringRank: 5,
    image: IMG + "3/34/Jesus_vs_Stevenson_2016_Rio_8cr.jpg/512px-Jesus_vs_Stevenson_2016_Rio_8cr.jpg",
    recordUrl: "https://en.wikipedia.org/wiki/Shakur_Stevenson",
    stance: "Southpaw", height: `5'7" (170 cm)`, reach: `68" (173 cm)`, age: 28, dob: "1997-06-28", hometown: "Newark, New Jersey, USA", debut: 2017, promoterId: "top-rank",
    currentTitles: ["WBO Super Lightweight Champion", "The Ring Super Lightweight Champion"], standing: "",
    bio: "An Olympic silver medalist with elite defensive instincts, Stevenson became a four-division world champion by outpointing Teófimo López for the Ring and WBO 140-pound titles in January 2026.",
    social: { instagram: "https://instagram.com/shakurstevenson", x: "https://x.com/shakurstevenson" },
    upcoming: [{ date: "2026-09-19", opponent: "Keyshawn Davis", event: "WBO Mandatory (targeted)", venue: "Newark, New Jersey", title: "Super Lightweight" }],
    recent: [
      { date: "2026-01-31", opponent: "Teófimo López", result: "W", method: "UD", round: 12, event: "Madison Square Garden, NYC" },
      { date: "2025-07-12", opponent: "William Zepeda", result: "W", method: "UD", round: 12, event: "Louis Armstrong Stadium, NYC" },
      { date: "2025-02-22", opponent: "Josh Padley", result: "W", method: "TKO", round: 9, event: "Riyadh, Saudi Arabia" },
      { date: "2024-07-06", opponent: "Artem Harutyunyan", result: "W", method: "UD", round: 12, event: "Prudential Center, Newark" },
      { date: "2023-11-16", opponent: "Edwin De Los Santos", result: "W", method: "UD", round: 12, event: "T-Mobile Arena, Las Vegas" },
      { date: "2023-04-08", opponent: "Shuichiro Yoshino", result: "W", method: "TKO", round: 6, event: "Prudential Center, Newark" },
      { date: "2022-09-23", opponent: "Robson Conceição", result: "W", method: "UD", round: 12, event: "Prudential Center, Newark" },
      { date: "2022-04-30", opponent: "Óscar Valdez", result: "W", method: "UD", round: 12, event: "MGM Grand, Las Vegas" },
      { date: "2021-10-23", opponent: "Jamel Herring", result: "W", method: "TKO", round: 10, event: "State Farm Arena, Atlanta" },
      { date: "2021-06-12", opponent: "Jeremiah Nakathila", result: "W", method: "UD", round: 12, event: "Virgin Hotels, Las Vegas" },
      { date: "2020-12-12", opponent: "Toka Khan Clary", result: "W", method: "UD", round: 10, event: "MGM Grand, Las Vegas" },
      { date: "2020-06-09", opponent: "Felix Caraballo", result: "W", method: "KO", round: 6, event: "MGM Grand, Las Vegas" },
    ],
    news: [
      { t: "Stevenson decisions Teófimo López to become a four-division champ", s: "ESPN", d: "2026-01-31", u: "https://www.espn.com/boxing/story/_/id/38550909/shakur-stevenson-biography-record-fights-more" },
      { t: "Stevenson in preliminary talks over his next opponent", s: "Sports Illustrated", d: "2026-06-05", u: "https://www.si.com/fannation/boxing/shakur-stevenson-reportedly-in-preliminary-talks-with-next-opponent" },
      { t: "Shakur Stevenson — fight record and bio", s: "DAZN", d: "2026-04-01", u: "https://www.dazn.com/en-US/news/boxing/shakur-stevenson-fight-record-career-bio-stats-next-bout-details/18jlgz0xcuo92zm7kbdsm9fjg" },
    ],
  },
  {
    id: "david-benavidez", name: "David Benavidez", nickname: "El Monstruo Mexicano", sport: "boxing", flag: "🇺🇸", nationality: "USA / Mexico", division: "Light Heavyweight",
    record: { w: 32, l: 0, d: 0, ko: 26 }, methods: { ko: 26, dec: 6 }, ringRank: 4,
    image: IMG + "8/8d/David_Benavidez_2024.png/512px-David_Benavidez_2024.png",
    recordUrl: "https://en.wikipedia.org/wiki/David_Benavidez",
    stance: "Orthodox", height: `6'2" (188 cm)`, reach: `74.5" (189 cm)`, age: 29, dob: "1996-12-17", hometown: "Phoenix, Arizona, USA", debut: 2013, promoterId: "pbc",
    currentTitles: ["WBC Light Heavyweight Champion", "WBA & WBO Cruiserweight Champion"], standing: "",
    bio: "The relentless 'Mexican Monster' became a three-division champion in 2026, holding the WBC light heavyweight title and adding the WBA and WBO cruiserweight belts by stopping Gilberto 'Zurdo' Ramírez.",
    social: { instagram: "https://instagram.com/benavidez300", x: "https://x.com/benavidez300" },
    upcoming: [{ date: "2026-12-12", opponent: "Dmitry Bivol", event: "Undisputed Light Heavyweight (targeted)", venue: "Riyadh, Saudi Arabia", title: "Light Heavyweight" }],
    recent: [
      { date: "2026-05-02", opponent: "Gilberto Ramírez", result: "W", method: "TKO", round: 6, event: "T-Mobile Arena, Las Vegas" },
      { date: "2025-11-22", opponent: "Anthony Yarde", result: "W", method: "TKO", round: 7, event: "ANB Arena, Riyadh" },
      { date: "2025-02-01", opponent: "David Morrell", result: "W", method: "UD", round: 12, event: "T-Mobile Arena, Las Vegas" },
      { date: "2024-06-15", opponent: "Oleksandr Gvozdyk", result: "W", method: "UD", round: 12, event: "MGM Grand, Las Vegas" },
      { date: "2023-11-25", opponent: "Demetrius Andrade", result: "W", method: "RTD", round: 6, event: "Michelob Ultra Arena, Las Vegas" },
      { date: "2023-03-25", opponent: "Caleb Plant", result: "W", method: "UD", round: 12, event: "MGM Grand, Las Vegas" },
      { date: "2022-05-21", opponent: "David Lemieux", result: "W", method: "TKO", round: 3, event: "Gila River Arena, Glendale" },
      { date: "2021-11-13", opponent: "Kyrone Davis", result: "W", method: "TKO", round: 7, event: "Footprint Center, Phoenix" },
      { date: "2021-03-13", opponent: "Ronald Ellis", result: "W", method: "TKO", round: 11, event: "Mohegan Sun, Montville" },
      { date: "2020-08-15", opponent: "Roamer Alexis Angulo", result: "W", method: "RTD", round: 10, event: "Mohegan Sun, Montville" },
      { date: "2019-09-28", opponent: "Anthony Dirrell", result: "W", method: "TKO", round: 9, event: "Crypto.com Arena, Los Angeles" },
      { date: "2019-03-16", opponent: "J'Leon Love", result: "W", method: "TKO", round: 2, event: "AT&T Stadium, Arlington" },
    ],
    news: [
      { t: "Benavidez stops Zurdo Ramírez to add the cruiserweight belts", s: "Premier Boxing Champions", d: "2026-05-02", u: "https://www.premierboxingchampions.com/david-benavidez" },
      { t: "Bivol vacates WBC belt; Benavidez promoted to full champion", s: "CBS Sports", d: "2026-04-10", u: "https://www.cbssports.com/boxing/news/dmitry-bivol-vacates-wbc-light-heavyweight-title-sanctioning-body-promotes-david-benavidez-to-full-champion/" },
      { t: "David Benavidez is the WBC Light Heavyweight Champion", s: "WBC", d: "2026-04-10", u: "https://wbcboxing.com/en/david-benavidez-is-wbc-light-heavyweight-champion/" },
    ],
  },
  {
    id: "devin-haney", name: "Devin Haney", nickname: "The Dream", sport: "boxing", flag: "🇺🇸", nationality: "USA", division: "Welterweight",
    record: { w: 33, l: 0, d: 0, nc: 1, ko: 15 }, methods: { ko: 15, dec: 18 }, ringRank: 6,
    image: IMG + "e/e0/Devin_Haney.jpg/512px-Devin_Haney.jpg",
    recordUrl: "https://en.wikipedia.org/wiki/Devin_Haney",
    stance: "Orthodox", height: `5'8" (173 cm)`, reach: `71" (180 cm)`, age: 27, dob: "1998-11-17", hometown: "Las Vegas, Nevada, USA", debut: 2015, promoterId: "matchroom",
    currentTitles: ["WBO Welterweight Champion"], standing: "",
    bio: "A former undisputed lightweight king, the smooth-boxing 'Dream' moved up and outpointed Brian Norman Jr. in November 2025 to capture the WBO welterweight title and a world title in a third weight class.",
    social: { instagram: "https://instagram.com/realdevinhaney", x: "https://x.com/realdevinhaney" },
    upcoming: [{ date: "2026-08-15", opponent: "Keyshawn Davis", event: "WBO Welterweight Mandatory (targeted)", venue: "Las Vegas, Nevada", title: "Welterweight" }],
    recent: [
      { date: "2025-11-22", opponent: "Brian Norman Jr.", result: "W", method: "UD", round: 12, event: "ANB Arena, Riyadh" },
      { date: "2025-05-02", opponent: "José Ramírez", result: "W", method: "UD", round: 12, event: "Times Square, NYC" },
      { date: "2024-04-20", opponent: "Ryan Garcia", result: "NC", method: "No Contest", round: 12, event: "Barclays Center, NYC" },
      { date: "2023-12-09", opponent: "Regis Prograis", result: "W", method: "UD", round: 12, event: "Chase Center, San Francisco" },
      { date: "2023-05-20", opponent: "Vasiliy Lomachenko", result: "W", method: "UD", round: 12, event: "MGM Grand, Las Vegas" },
      { date: "2022-10-16", opponent: "George Kambosos Jr.", result: "W", method: "UD", round: 12, event: "Rod Laver Arena, Melbourne" },
      { date: "2022-06-05", opponent: "George Kambosos Jr.", result: "W", method: "UD", round: 12, event: "Marvel Stadium, Melbourne" },
      { date: "2021-12-04", opponent: "Joseph Diaz Jr.", result: "W", method: "UD", round: 12, event: "MGM Grand, Las Vegas" },
      { date: "2021-05-29", opponent: "Jorge Linares", result: "W", method: "UD", round: 12, event: "Michelob Ultra Arena, Las Vegas" },
      { date: "2020-11-07", opponent: "Yuriorkis Gamboa", result: "W", method: "UD", round: 12, event: "Hard Rock Live, Hollywood FL" },
      { date: "2019-11-09", opponent: "Alfredo Santiago", result: "W", method: "UD", round: 12, event: "Staples Center, Los Angeles" },
      { date: "2019-09-13", opponent: "Zaur Abdullaev", result: "W", method: "RTD", round: 4, event: "Hulu Theater, New York" },
    ],
    news: [
      { t: "WBO orders Haney to defend welterweight title vs Keyshawn Davis", s: "Boxing News Online", d: "2026-06-12", u: "https://boxingnewsonline.net/news/haney-blocked-from-facing-stevenson/" },
      { t: "Haney outpoints Brian Norman Jr. for the WBO welterweight title", s: "DAZN", d: "2025-11-22", u: "https://www.dazn.com/en-US/news/boxing/devin-haney-vs-brian-norman-fight-time-ringwalks-running-order-streaming-watch/sctqlbku77ep1etbp3j1oe70r" },
      { t: "Devin Haney — record and title history", s: "Wikipedia", d: "2026-06-01", u: "https://en.wikipedia.org/wiki/Devin_Haney" },
    ],
  },
  {
    id: "oscar-collazo", name: "Oscar Collazo", nickname: "El Pupilo", sport: "boxing", flag: "🇵🇷", nationality: "Puerto Rico", division: "Minimumweight",
    record: { w: 14, l: 0, d: 0, ko: 11 }, methods: { ko: 11, dec: 3 }, ringRank: 10,
    image: "https://images.ctfassets.net/lg76kxmf55ue/5jgMr0qKlALucDBl9tLraS/15cc67144cac18fc877949d45e1a7abd/OscarCollazo.png?w=600&h=750&fit=fill&f=face&fm=jpg&q=80",
    recordUrl: "https://en.wikipedia.org/wiki/Oscar_Collazo_(boxer)",
    stance: "Southpaw", height: `5'4" (163 cm)`, reach: `64" (163 cm)`, age: 28, dob: "1997-04-17", hometown: "Salinas, Puerto Rico", debut: 2021, promoterId: "golden-boy",
    currentTitles: ["WBA & WBO Minimumweight Champion", "The Ring Minimumweight Champion"], standing: "",
    bio: "The pride of boxing's smallest division, Collazo is the unified WBA and WBO minimumweight champion. He blasted out Neider Valdez in two rounds in June 2026 and is hunting undisputed status at 105 pounds.",
    social: { instagram: "https://instagram.com/oscarcollazo_", x: "https://x.com/oscarcollazo_" },
    upcoming: [],
    recent: [
      { date: "2026-06-20", opponent: "Neider Valdez", result: "W", method: "KO", round: 2, event: "Frontwave Arena, Oceanside" },
      { date: "2026-03-14", opponent: "Jesus Haro", result: "W", method: "RTD", round: 6, event: "Honda Center, Anaheim" },
      { date: "2025-09-20", opponent: "Jayson Vayson", result: "W", method: "KO", round: 7, event: "Fantasy Springs, Indio" },
      { date: "2025-03-29", opponent: "Edwin Cano", result: "W", method: "KO", round: 5, event: "Poliforum, Cancún" },
      { date: "2024-11-16", opponent: "Knockout CP Freshmart", result: "W", method: "TKO", round: 7, event: "The Venue, Riyadh" },
      { date: "2024-06-07", opponent: "Gerardo Zapata", result: "W", method: "UD", round: 12, event: "Turning Stone, Verona NY" },
      { date: "2024-01-27", opponent: "Reyneris Gutierrez", result: "W", method: "TKO", round: 3, event: "Footprint Center, Phoenix" },
      { date: "2023-08-26", opponent: "Garen Diagan", result: "W", method: "RTD", round: 6, event: "Roberto Clemente Coliseum, San Juan" },
      { date: "2023-05-27", opponent: "Melvin Jerusalem", result: "W", method: "RTD", round: 7, event: "Fantasy Springs, Indio" },
      { date: "2023-01-28", opponent: "Yudel Reyes", result: "W", method: "KO", round: 5, event: "YouTube Theater, Inglewood" },
      { date: "2022-07-16", opponent: "Vic Saludar", result: "W", method: "UD", round: 12, event: "Crypto.com Arena, Los Angeles" },
      { date: "2021-12-03", opponent: "Pedro Villegas", result: "W", method: "TKO", round: 3, event: "Los Andes, Panama City" },
    ],
    news: [
      { t: "Collazo blasts Neider Valdez in two rounds in Oceanside", s: "FIGHTMAG", d: "2026-06-20", u: "https://www.fightmag.com/boxing-oscar-collazo-vs-neider-valdez-live-results/" },
      { t: "Collazo eyes a multi-divisional blueprint after title defense", s: "No Smoke Boxing", d: "2026-06-21", u: "https://nosmokeboxing.com/oscar-collazo-eyes-multi-divisional-blueprint-after-june-20/" },
      { t: "Oscar Collazo — Golden Boy fighter profile", s: "Golden Boy", d: "2026-05-01", u: "https://www.goldenboy.com/fighter-profile/oscar-collazo/" },
    ],
  },

  /* ===================== MMA — UFC P4P TOP 15 ===================== */
  {
    id: "islam-makhachev", name: "Islam Makhachev", nickname: "", sport: "mma", flag: "🇷🇺", nationality: "Russia (Dagestan)", division: "Welterweight",
    record: { w: 28, l: 1, d: 0, ko: 6, sub: 12, dec: 10 }, methods: { ko: 6, sub: 12, dec: 10 }, ufcRank: 1,
    image: IMG + "9/95/Islam_Makhachev_and_Sergey_Melikov_2025_%28cropped%29.jpg/512px-Islam_Makhachev_and_Sergey_Melikov_2025_%28cropped%29.jpg",
    recordUrl: "https://en.wikipedia.org/wiki/Islam_Makhachev",
    stance: "Southpaw", height: `5'10" (178 cm)`, reach: `70.5" (179 cm)`, age: 34, dob: "1991-10-27", hometown: "Makhachkala, Dagestan, Russia", debut: 2010, promoterId: "ufc",
    currentTitles: ["UFC Welterweight Champion"], standing: "",
    bio: "A protégé of Khabib Nurmagomedov, Makhachev tied the UFC's all-time win-streak record before moving up to take the welterweight title from Jack Della Maddalena in November 2025. He is the consensus pound-for-pound No. 1.",
    social: { instagram: "https://instagram.com/islam_makhachev", x: "https://x.com/makhachevmma" },
    upcoming: [{ date: "2026-08-15", opponent: "Ian Machado Garry", event: "UFC 330 · Philadelphia", venue: "Xfinity Mobile Arena, Philadelphia", title: "UFC Welterweight" }],
    recent: [
      { date: "2025-11-15", opponent: "Jack Della Maddalena", result: "W", method: "Decision (UD)", round: 5, event: "UFC 322 · for the WW title" },
      { date: "2025-01-18", opponent: "Renato Moicano", result: "W", method: "Submission (brabo)", round: 1, event: "UFC 311" },
      { date: "2024-06-01", opponent: "Dustin Poirier", result: "W", method: "Submission (brabo)", round: 5, event: "UFC 302" },
      { date: "2023-10-21", opponent: "Alexander Volkanovski", result: "W", method: "KO (head kick)", round: 1, event: "UFC 294" },
      { date: "2023-02-12", opponent: "Alexander Volkanovski", result: "W", method: "Decision (UD)", round: 5, event: "UFC 284" },
      { date: "2022-10-22", opponent: "Charles Oliveira", result: "W", method: "Submission (arm-triangle)", round: 2, event: "UFC 280 · for the LW title" },
      { date: "2022-02-26", opponent: "Bobby Green", result: "W", method: "TKO (punches)", round: 1, event: "UFC Fight Night" },
      { date: "2021-10-30", opponent: "Dan Hooker", result: "W", method: "Submission (kimura)", round: 1, event: "UFC 267" },
      { date: "2021-07-17", opponent: "Thiago Moisés", result: "W", method: "Submission (RNC)", round: 4, event: "UFC on ESPN" },
      { date: "2021-03-06", opponent: "Drew Dober", result: "W", method: "Submission (arm-triangle)", round: 3, event: "UFC 259" },
    ],
    news: [
      { t: "Makhachev decisions Della Maddalena to win the welterweight title", s: "UFC", d: "2025-11-15", u: "https://www.ufc.com/athlete/islam-makhachev" },
      { t: "Makhachev vs Ian Garry official for the UFC 330 main event", s: "Yahoo Sports", d: "2026-06-01", u: "https://sports.yahoo.com/articles/islam-makhachev-vs-ian-garry-184606920.html" },
      { t: "Makhachev reveals timetable for his first welterweight defense", s: "Sports Illustrated", d: "2026-04-20", u: "https://www.si.com/fannation/mma/news/islam-makhachev-reveals-timetable-for-first-ufc-welterweight-title-defense-in-2026" },
    ],
  },
  {
    id: "alexander-volkanovski", name: "Alexander Volkanovski", nickname: "The Great", sport: "mma", flag: "🇦🇺", nationality: "Australia", division: "Featherweight",
    record: { w: 28, l: 4, d: 0, ko: 13, sub: 3, dec: 12 }, methods: { ko: 13, sub: 3, dec: 12 }, ufcRank: 2,
    image: IMG + "0/0f/Alexander_Volkanovski_at_UFC_232.jpg/512px-Alexander_Volkanovski_at_UFC_232.jpg",
    recordUrl: "https://en.wikipedia.org/wiki/Alexander_Volkanovski",
    stance: "Orthodox", height: `5'6" (168 cm)`, reach: `71.5" (182 cm)`, age: 37, dob: "1988-09-29", hometown: "Wollongong, New South Wales, Australia", debut: 2012, promoterId: "ufc",
    currentTitles: ["UFC Featherweight Champion"], standing: "",
    bio: "A former rugby front-rower turned all-time great, the two-time featherweight champion defended his belt against Diego Lopes in February 2026 and is eyeing Movsar Evloev and more champ-vs-champ history.",
    social: { instagram: "https://instagram.com/alexvolkanovski", x: "https://x.com/alexvolkanovski" },
    upcoming: [{ date: "2026-09-12", opponent: "Movsar Evloev", event: "UFC Featherweight Title (targeted)", venue: "TBA", title: "UFC Featherweight" }],
    recent: [
      { date: "2026-02-01", opponent: "Diego Lopes", result: "W", method: "Decision (UD)", round: 5, event: "UFC 325" },
      { date: "2025-04-12", opponent: "Diego Lopes", result: "W", method: "Decision (UD)", round: 5, event: "UFC 314 · for the vacant title" },
      { date: "2024-02-17", opponent: "Ilia Topuria", result: "L", method: "KO (punch)", round: 2, event: "UFC 298" },
      { date: "2023-10-21", opponent: "Islam Makhachev", result: "L", method: "KO (head kick)", round: 1, event: "UFC 294" },
      { date: "2023-07-08", opponent: "Yair Rodríguez", result: "W", method: "TKO (punches)", round: 3, event: "UFC 290" },
      { date: "2023-02-12", opponent: "Islam Makhachev", result: "L", method: "Decision (UD)", round: 5, event: "UFC 284" },
      { date: "2022-07-02", opponent: "Max Holloway", result: "W", method: "Decision (UD)", round: 5, event: "UFC 276" },
      { date: "2022-04-09", opponent: "Chan Sung Jung", result: "W", method: "TKO (punches)", round: 4, event: "UFC 273" },
      { date: "2021-09-25", opponent: "Brian Ortega", result: "W", method: "Decision (UD)", round: 5, event: "UFC 266" },
      { date: "2020-07-12", opponent: "Max Holloway", result: "W", method: "Decision (SD)", round: 5, event: "UFC 251" },
    ],
    news: [
      { t: "Volkanovski outpoints Diego Lopes in the UFC 325 rematch", s: "ESPN", d: "2026-02-01", u: "https://www.espn.com/mma/fighter/_/id/3949584/alexander-volkanovski" },
      { t: "Volkanovski calls for Movsar Evloev next at featherweight", s: "Bloody Elbow", d: "2026-05-02", u: "https://bloodyelbow.com/2026/05/02/alexander-volkanovski-provides-update-on-targeted-ufc-return-as-he-personally-calls-for-contender/" },
      { t: "Volkanovski eyes a champ-vs-champ superfight with Gaethje", s: "EssentiallySports", d: "2026-06-10", u: "https://www.essentiallysports.com/ufc-mma-news-alexander-volkanovski-eyes-champ-vs-champ-fight-against-justin-gaethje-amid-arman-tsarukyan-uncertainty/" },
    ],
  },
  {
    id: "petr-yan", name: "Petr Yan", nickname: "No Mercy", sport: "mma", flag: "🇷🇺", nationality: "Russia", division: "Bantamweight",
    record: { w: 20, l: 5, d: 0, ko: 8, sub: 1, dec: 11 }, methods: { ko: 8, sub: 1, dec: 11 }, ufcRank: 3,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/PetrYan%20(cropped).jpg?width=480",
    recordUrl: "https://en.wikipedia.org/wiki/Petr_Yan",
    stance: "Switch", height: `5'7" (170 cm)`, reach: `67" (170 cm)`, age: 33, dob: "1993-02-11", hometown: "Dudinka, Russia", debut: 2014, promoterId: "ufc",
    currentTitles: ["UFC Bantamweight Champion"], standing: "",
    bio: "A technically immaculate boxer-grappler from Siberia, the two-time champion reclaimed the 135-pound title by outpointing Merab Dvalishvili in December 2025. He returns from minor back surgery in summer 2026.",
    social: { instagram: "https://instagram.com/petr_yan", x: "https://x.com/petryanufc" },
    upcoming: [{ date: "2026-08-23", opponent: "Merab Dvalishvili", event: "Bantamweight Title Trilogy (targeted)", venue: "TBA", title: "UFC Bantamweight" }],
    recent: [
      { date: "2025-12-06", opponent: "Merab Dvalishvili", result: "W", method: "Decision (UD)", round: 5, event: "UFC 323 · for the BW title" },
      { date: "2025-07-26", opponent: "Marcus McGhee", result: "W", method: "Decision (UD)", round: 3, event: "UFC on ABC 9" },
      { date: "2024-11-23", opponent: "Deiveson Figueiredo", result: "W", method: "Decision (UD)", round: 5, event: "UFC Fight Night 248" },
      { date: "2024-03-09", opponent: "Song Yadong", result: "W", method: "Decision (UD)", round: 3, event: "UFC 299" },
      { date: "2023-03-11", opponent: "Merab Dvalishvili", result: "L", method: "Decision (UD)", round: 5, event: "UFC Fight Night" },
      { date: "2022-10-22", opponent: "Sean O'Malley", result: "L", method: "Decision (SD)", round: 3, event: "UFC 280" },
      { date: "2022-04-09", opponent: "Aljamain Sterling", result: "L", method: "Decision (SD)", round: 5, event: "UFC 273" },
      { date: "2021-10-30", opponent: "Cory Sandhagen", result: "W", method: "Decision (UD)", round: 5, event: "UFC 267" },
      { date: "2021-03-06", opponent: "Aljamain Sterling", result: "L", method: "DQ (illegal knee)", round: 4, event: "UFC 259" },
      { date: "2020-07-12", opponent: "José Aldo", result: "W", method: "TKO (punches)", round: 5, event: "UFC 251" },
    ],
    news: [
      { t: "Yan reclaims the bantamweight title with a decision over Dvalishvili", s: "ESPN", d: "2025-12-06", u: "https://www.espn.com/mma/fighter/_/id/4293517/petr-yan" },
      { t: "Champ Yan targeted for a summer return after back surgery", s: "CBS Sports", d: "2026-03-15", u: "https://www.cbssports.com/ufc/news/petr-yan-ufc-bantamweight-champion-back-surgery-injury-return-timetable/" },
      { t: "O'Malley crowns Yan the bantamweight GOAT", s: "NY Fights", d: "2026-05-01", u: "https://nyfights.com/mma/sean-o-malley-on-petr-yan-merab-dvalishvili/" },
    ],
  },
  {
    id: "justin-gaethje", name: "Justin Gaethje", nickname: "The Highlight", sport: "mma", flag: "🇺🇸", nationality: "USA", division: "Lightweight",
    record: { w: 28, l: 5, d: 0, ko: 21, sub: 0, dec: 7 }, methods: { ko: 21, sub: 0, dec: 7 }, ufcRank: 4,
    image: IMG + "8/86/UFC_Freedom_250%2C_the_mixed_martial_arts_event_produced_by_the_Ultimate_Fighting_Championship%2C_Sunday%2C_June_14%2C_2026%2C_in_the_Grand_Foyer_of_the_White_House_-_67%28cropped%29.jpg/512px-thumbnail.jpg",
    recordUrl: "https://en.wikipedia.org/wiki/Justin_Gaethje",
    stance: "Orthodox", height: `5'11" (180 cm)`, reach: `70" (178 cm)`, age: 37, dob: "1988-11-14", hometown: "Safford, Arizona, USA", debut: 2011, promoterId: "ufc",
    currentTitles: ["UFC Lightweight Champion"], standing: "",
    bio: "The most violent man in the lightweight division pulled off a stunning upset, stopping previously unbeaten Ilia Topuria at the White House in June 2026 to become — at 37 — the oldest UFC lightweight champion in history.",
    social: { instagram: "https://instagram.com/justin_gaethje", x: "https://x.com/justin_gaethje" },
    upcoming: [],
    recent: [
      { date: "2026-06-14", opponent: "Ilia Topuria", result: "W", method: "TKO", round: 4, event: "UFC Freedom 250 · White House" },
      { date: "2026-01-24", opponent: "Paddy Pimblett", result: "W", method: "Decision (UD)", round: 5, event: "UFC 324 · interim title" },
      { date: "2025-03-08", opponent: "Rafael Fiziev", result: "W", method: "Decision (UD)", round: 3, event: "UFC 313" },
      { date: "2024-04-13", opponent: "Max Holloway", result: "L", method: "KO (punch)", round: 5, event: "UFC 300 · BMF title" },
      { date: "2023-07-29", opponent: "Dustin Poirier", result: "W", method: "KO (head kick)", round: 2, event: "UFC 291 · BMF title" },
      { date: "2023-03-18", opponent: "Rafael Fiziev", result: "W", method: "Decision (MD)", round: 3, event: "UFC 286" },
      { date: "2022-05-07", opponent: "Charles Oliveira", result: "L", method: "Submission (RNC)", round: 1, event: "UFC 274" },
      { date: "2021-11-06", opponent: "Michael Chandler", result: "W", method: "Decision (UD)", round: 3, event: "UFC 268" },
      { date: "2020-10-24", opponent: "Khabib Nurmagomedov", result: "L", method: "Submission (triangle)", round: 2, event: "UFC 254" },
      { date: "2020-05-09", opponent: "Tony Ferguson", result: "W", method: "TKO (punches)", round: 5, event: "UFC 249 · interim title" },
    ],
    news: [
      { t: "Gaethje TKOs Topuria at the White House to claim the LW title", s: "Sunday Guardian", d: "2026-06-14", u: "https://sundayguardianlive.com/sports/will-justin-gaethje-fight-again-in-2026-ufc-white-house-champion-drops-major-return-update-after-ilia-topuria-victory-209554/" },
      { t: "Gaethje doubts he fights again in 2026 after his title win", s: "Yahoo Sports", d: "2026-06-16", u: "https://sports.yahoo.com/articles/ufc-lightweight-champion-justin-gaethje-134023365.html" },
      { t: "Justin Gaethje is the new lightweight champion", s: "RotoBaller", d: "2026-06-15", u: "https://www.rotoballer.com/player-news/justin-gaethje-is-the-new-lightweight-champion/1876494" },
    ],
  },
  {
    id: "ilia-topuria", name: "Ilia Topuria", nickname: "El Matador", sport: "mma", flag: "🇪🇸", nationality: "Spain / Georgia", division: "Lightweight",
    record: { w: 17, l: 1, d: 0, ko: 9, sub: 5, dec: 3 }, methods: { ko: 9, sub: 5, dec: 3 }, ufcRank: 5,
    image: IMG + "7/79/Ilia_Topuria_in_the_Oval_Office_%28while_President_Donald_J._Trump_is_holding_a_meeting_with_UFC_fighters%29.jpg/512px-Ilia_Topuria_in_the_Oval_Office_%28while_President_Donald_J._Trump_is_holding_a_meeting_with_UFC_fighters%29.jpg",
    recordUrl: "https://en.wikipedia.org/wiki/Ilia_Topuria",
    stance: "Orthodox", height: `5'7" (170 cm)`, reach: `69" (175 cm)`, age: 29, dob: "1997-01-21", hometown: "Alicante, Spain (born Halle, Germany)", debut: 2015, promoterId: "ufc",
    currentTitles: [], standing: "Former Two-Division UFC Champion",
    bio: "A surgical boxer with grappling pedigree, Spain's first UFC champion became the promotion's first undefeated two-division titleholder. Justin Gaethje handed him the first loss of his career in June 2026 at the White House.",
    social: { instagram: "https://instagram.com/iliatopuria", x: "https://x.com/topuriailia" },
    upcoming: [],
    recent: [
      { date: "2026-06-14", opponent: "Justin Gaethje", result: "L", method: "TKO", round: 4, event: "UFC Freedom 250 · White House" },
      { date: "2025-06-28", opponent: "Charles Oliveira", result: "W", method: "KO (punches)", round: 1, event: "UFC 317 · vacant LW title" },
      { date: "2024-10-26", opponent: "Max Holloway", result: "W", method: "KO (punches)", round: 3, event: "UFC 308 · FW title" },
      { date: "2024-02-17", opponent: "Alexander Volkanovski", result: "W", method: "KO (punch)", round: 2, event: "UFC 298 · for the FW title" },
      { date: "2023-06-24", opponent: "Josh Emmett", result: "W", method: "Decision (UD)", round: 5, event: "UFC on ABC" },
      { date: "2022-12-10", opponent: "Bryce Mitchell", result: "W", method: "Submission (arm-triangle)", round: 2, event: "UFC 282" },
      { date: "2022-03-19", opponent: "Jai Herbert", result: "W", method: "KO (punches)", round: 2, event: "UFC Fight Night" },
      { date: "2021-07-10", opponent: "Ryan Hall", result: "W", method: "KO (punches)", round: 1, event: "UFC 264" },
      { date: "2020-12-05", opponent: "Damon Jackson", result: "W", method: "KO (punches)", round: 1, event: "UFC on ESPN" },
      { date: "2020-10-11", opponent: "Youssef Zalal", result: "W", method: "Decision (UD)", round: 3, event: "UFC Fight Night" },
    ],
    news: [
      { t: "Topuria suffers his first pro loss to Gaethje at Freedom 250", s: "Al Jazeera", d: "2026-06-14", u: "https://www.aljazeera.com/sports/2026/6/11/ilia-topuria-vs-justin-gaethje-title-fight-at-ufc-freedom-250-all-to-know" },
      { t: "Gaethje shuts down a Topuria rematch", s: "Yahoo Sports", d: "2026-06-16", u: "https://sports.yahoo.com/articles/justin-gaethje-shuts-down-ilia-201913615.html" },
      { t: "Ilia Topuria — UFC record, biography & profile", s: "ESPN", d: "2026-06-01", u: "https://www.espn.com/mma/fighter/_/id/4350812/ilia-topuria" },
    ],
  },
  {
    id: "tom-aspinall", name: "Tom Aspinall", nickname: "", sport: "mma", flag: "🇬🇧", nationality: "England", division: "Heavyweight",
    record: { w: 15, l: 3, d: 0, nc: 1, ko: 11, sub: 4, dec: 0 }, methods: { ko: 11, sub: 4, dec: 0 }, ufcRank: 6,
    image: "https://www.ufc.com/images/styles/athlete_bio_full_body/s3/2025-10/ASPINALL_TOM_L_BELT_10-25.png?itok=wdUr8VUg",
    recordUrl: "https://en.wikipedia.org/wiki/Tom_Aspinall",
    stance: "Orthodox", height: `6'5" (196 cm)`, reach: `78" (198 cm)`, age: 33, dob: "1993-04-11", hometown: "Salford, England", debut: 2014, promoterId: "ufc",
    currentTitles: ["UFC Heavyweight Champion"], standing: "",
    bio: "Frighteningly fast for a heavyweight, Aspinall combines black-belt grappling with one-punch power. His first title defense against Ciryl Gane was ruled a no-contest after eye pokes; medically cleared, he targets a September unification.",
    social: { instagram: "https://instagram.com/aspinallmma", x: "https://x.com/aspinallmma" },
    upcoming: [{ date: "2026-09-26", opponent: "Ciryl Gane", event: "Undisputed Heavyweight (targeted)", venue: "Paris, France", title: "UFC Heavyweight" }],
    recent: [
      { date: "2025-10-25", opponent: "Ciryl Gane", result: "NC", method: "No Contest (eye poke)", round: 1, event: "UFC 321" },
      { date: "2024-07-27", opponent: "Curtis Blaydes", result: "W", method: "KO (punches)", round: 1, event: "UFC 304 · interim title" },
      { date: "2023-11-11", opponent: "Sergei Pavlovich", result: "W", method: "KO (punches)", round: 1, event: "UFC 295 · interim title" },
      { date: "2023-07-22", opponent: "Marcin Tybura", result: "W", method: "TKO (elbows)", round: 1, event: "UFC Fight Night 224" },
      { date: "2022-07-23", opponent: "Curtis Blaydes", result: "L", method: "TKO (knee injury)", round: 1, event: "UFC Fight Night" },
      { date: "2022-03-19", opponent: "Alexander Volkov", result: "W", method: "Submission (armbar)", round: 1, event: "UFC Fight Night" },
      { date: "2021-09-04", opponent: "Serghei Spivac", result: "W", method: "TKO (elbows)", round: 1, event: "UFC Fight Night" },
      { date: "2021-02-20", opponent: "Andrei Arlovski", result: "W", method: "Submission (RNC)", round: 2, event: "UFC Fight Night" },
      { date: "2020-10-10", opponent: "Alan Baudot", result: "W", method: "TKO (elbows)", round: 1, event: "UFC Fight Night" },
      { date: "2020-07-26", opponent: "Jake Collier", result: "W", method: "TKO (knee)", round: 1, event: "UFC on ESPN" },
    ],
    news: [
      { t: "Aspinall accepts Gane's challenge for the undisputed title", s: "ESPN", d: "2026-06-16", u: "https://www.espn.com/ufc/story/_/id/49075259/ufc-heavyweight-champ-tom-aspinall-accepts-ciryl-gane-challenge-there" },
      { t: "Aspinall ready for a September return vs Gane in Paris", s: "Blueprint", d: "2026-06-18", u: "https://blueprint.ng/ufc-heavyweight-aspinall-ready-for-september-2026-return-against-gane/" },
      { t: "Aspinall shuts down boxing rumors: 'more to do in the UFC'", s: "Bloody Elbow", d: "2026-04-27", u: "https://bloodyelbow.com/2026/04/27/tom-aspinall-shuts-down-boxing-rumors-ive-got-more-stuff-to-do-with-the-ufc/" },
    ],
  },
  {
    id: "sean-strickland", name: "Sean Strickland", nickname: "Tarzan", sport: "mma", flag: "🇺🇸", nationality: "USA", division: "Middleweight",
    record: { w: 31, l: 7, d: 0, ko: 12, sub: 4, dec: 15 }, methods: { ko: 12, sub: 4, dec: 15 }, ufcRank: 7,
    image: IMG + "4/44/Sean_Strickland_at_UFN_200.png/512px-Sean_Strickland_at_UFN_200.png",
    recordUrl: "https://en.wikipedia.org/wiki/Sean_Strickland",
    stance: "Switch", height: `6'1" (185 cm)`, reach: `76" (193 cm)`, age: 35, dob: "1991-02-27", hometown: "Anaheim, California, USA", debut: 2008, promoterId: "ufc",
    currentTitles: ["UFC Middleweight Champion"], standing: "",
    bio: "An iron-chinned, high-volume striker with a famously unfiltered personality, 'Tarzan' regained the middleweight title in May 2026 by handing Khamzat Chimaev the first loss of his career via split decision.",
    social: { instagram: "https://instagram.com/stricklandmma", x: "https://x.com/stricklandmma" },
    upcoming: [],
    recent: [
      { date: "2026-05-09", opponent: "Khamzat Chimaev", result: "W", method: "Decision (SD)", round: 5, event: "UFC 328 · for the MW title" },
      { date: "2026-02-21", opponent: "Anthony Hernandez", result: "W", method: "TKO (punches)", round: 3, event: "UFC Fight Night 267" },
      { date: "2025-02-09", opponent: "Dricus du Plessis", result: "L", method: "Decision (UD)", round: 5, event: "UFC 312 · MW title" },
      { date: "2024-06-01", opponent: "Paulo Costa", result: "W", method: "Decision (SD)", round: 5, event: "UFC 302" },
      { date: "2024-01-20", opponent: "Dricus du Plessis", result: "L", method: "Decision (SD)", round: 5, event: "UFC 297 · MW title" },
      { date: "2023-09-10", opponent: "Israel Adesanya", result: "W", method: "Decision (UD)", round: 5, event: "UFC 293 · won the title" },
      { date: "2023-07-01", opponent: "Abusupiyan Magomedov", result: "W", method: "TKO (punches)", round: 2, event: "UFC on ESPN 48" },
      { date: "2023-01-14", opponent: "Nassourdine Imavov", result: "W", method: "Decision (UD)", round: 5, event: "UFC Fight Night" },
      { date: "2022-12-17", opponent: "Jared Cannonier", result: "L", method: "Decision (SD)", round: 5, event: "UFC Fight Night 216" },
      { date: "2022-07-02", opponent: "Alex Pereira", result: "L", method: "KO (punches)", round: 1, event: "UFC 276" },
    ],
    news: [
      { t: "Strickland edges Chimaev by split decision to regain the MW title", s: "Al Jazeera", d: "2026-05-10", u: "https://www.aljazeera.com/sports/2026/5/10/strickland-vs-chimaev-ufc-328-strickland-downs-chimaev-on-split" },
      { t: "UFC 328: Chimaev vs Strickland — full results & highlights", s: "UFC", d: "2026-05-09", u: "https://www.ufc.com/news/ufc-328-chimaev-vs-strickland-results-highlights-main-card-winners-interviews-newark" },
      { t: "Sean Strickland — record, stats & profile", s: "ESPN", d: "2026-06-01", u: "https://www.espn.com/mma/fighter/_/id/3093653/sean-strickland" },
    ],
  },
  {
    id: "alex-pereira", name: "Alex Pereira", nickname: "Poatan", sport: "mma", flag: "🇧🇷", nationality: "Brazil", division: "Light Heavyweight",
    record: { w: 13, l: 3, d: 0, ko: 9, sub: 0, dec: 4 }, methods: { ko: 9, sub: 0, dec: 4 }, ufcRank: 8,
    image: IMG + "c/c7/Alex_Pereira_in_the_Oval_Office_%28while_President_Donald_J._Trump_is_holding_a_meeting_with_UFC_fighters%29.jpg/512px-Alex_Pereira_in_the_Oval_Office_%28while_President_Donald_J._Trump_is_holding_a_meeting_with_UFC_fighters%29.jpg",
    recordUrl: "https://en.wikipedia.org/wiki/Alex_Pereira",
    stance: "Orthodox", height: `6'4" (193 cm)`, reach: `79" (201 cm)`, age: 38, dob: "1987-07-07", hometown: "São Paulo, Brazil", debut: 2015, promoterId: "ufc",
    currentTitles: [], standing: "Former Two-Division UFC Champion",
    bio: "A two-division kickboxing legend turned UFC double-champ, 'Poatan' vacated his light heavyweight title in 2026 to chase heavyweight gold, but was stopped by Ciryl Gane in their June interim-title clash at the White House.",
    social: { instagram: "https://instagram.com/alexpoatanpereira", x: "https://x.com/alexpereiramma" },
    upcoming: [],
    recent: [
      { date: "2026-06-14", opponent: "Ciryl Gane", result: "L", method: "TKO (punches)", round: 2, event: "UFC Freedom 250 · interim HW title" },
      { date: "2025-10-04", opponent: "Magomed Ankalaev", result: "W", method: "TKO (punches)", round: 1, event: "UFC 320 · won LHW title" },
      { date: "2025-03-08", opponent: "Magomed Ankalaev", result: "L", method: "Decision (UD)", round: 5, event: "UFC 313 · LHW title" },
      { date: "2024-10-05", opponent: "Khalil Rountree Jr.", result: "W", method: "TKO (punches)", round: 4, event: "UFC 307" },
      { date: "2024-06-29", opponent: "Jiří Procházka", result: "W", method: "TKO (head kick)", round: 2, event: "UFC 303" },
      { date: "2024-04-13", opponent: "Jamahal Hill", result: "W", method: "KO (punches)", round: 1, event: "UFC 300" },
      { date: "2023-11-11", opponent: "Jiří Procházka", result: "W", method: "TKO (elbows)", round: 2, event: "UFC 295 · won LHW title" },
      { date: "2023-07-29", opponent: "Jan Błachowicz", result: "W", method: "Decision (SD)", round: 3, event: "UFC 291" },
      { date: "2023-04-08", opponent: "Israel Adesanya", result: "L", method: "KO (punches)", round: 2, event: "UFC 287" },
      { date: "2022-11-12", opponent: "Israel Adesanya", result: "W", method: "TKO (punches)", round: 5, event: "UFC 281 · won MW title" },
    ],
    news: [
      { t: "Gane stops Pereira in round two at UFC Freedom 250", s: "ESPN", d: "2026-06-14", u: "https://www.espn.com/mma/fighter/_/id/4705658/alex-pereira" },
      { t: "Pereira weighs a return to light heavyweight or heavyweight", s: "BetMGM", d: "2026-06-18", u: "https://sports.betmgm.com/en/blog/ufc/when-is-alex-pereira-next-fight-bm05/" },
      { t: "Alex Pereira — career record and titles", s: "Wikipedia", d: "2026-06-01", u: "https://en.wikipedia.org/wiki/Alex_Pereira" },
    ],
  },
  {
    id: "merab-dvalishvili", name: "Merab Dvalishvili", nickname: "The Machine", sport: "mma", flag: "🇬🇪", nationality: "Georgia", division: "Bantamweight",
    record: { w: 21, l: 5, d: 0, ko: 3, sub: 2, dec: 16 }, methods: { ko: 3, sub: 2, dec: 16 }, ufcRank: 9,
    image: IMG + "6/66/Merab_Dvalishvili_at_UFC_316_%28cropped%29.jpg/512px-Merab_Dvalishvili_at_UFC_316_%28cropped%29.jpg",
    recordUrl: "https://en.wikipedia.org/wiki/Merab_Dvalishvili",
    stance: "Orthodox", height: `5'6" (168 cm)`, reach: `68" (173 cm)`, age: 35, dob: "1991-01-10", hometown: "Tbilisi, Georgia", debut: 2014, promoterId: "ufc",
    currentTitles: [], standing: "Former UFC Bantamweight Champion",
    bio: "Owner of arguably the best cardio in MMA, 'The Machine' set takedown records during his title reign before dropping the belt to Petr Yan in their December 2025 rematch. An immediate trilogy is expected.",
    social: { instagram: "https://instagram.com/merab_dvalishvili", x: "https://x.com/merabdvalishvil" },
    upcoming: [{ date: "2026-08-23", opponent: "Petr Yan", event: "Bantamweight Title Trilogy (targeted)", venue: "TBA", title: "UFC Bantamweight" }],
    recent: [
      { date: "2025-12-06", opponent: "Petr Yan", result: "L", method: "Decision (UD)", round: 5, event: "UFC 323 · BW title" },
      { date: "2025-10-04", opponent: "Cory Sandhagen", result: "W", method: "Decision (UD)", round: 5, event: "UFC 320 · title defense" },
      { date: "2025-06-07", opponent: "Sean O'Malley", result: "W", method: "Submission (north-south)", round: 3, event: "UFC 316 · title defense" },
      { date: "2025-01-18", opponent: "Umar Nurmagomedov", result: "W", method: "Decision (UD)", round: 5, event: "UFC 311 · title defense" },
      { date: "2024-09-14", opponent: "Sean O'Malley", result: "W", method: "Decision (UD)", round: 5, event: "UFC 306 · won the title" },
      { date: "2024-02-17", opponent: "Henry Cejudo", result: "W", method: "Decision (UD)", round: 3, event: "UFC 298" },
      { date: "2023-03-11", opponent: "Petr Yan", result: "W", method: "Decision (UD)", round: 5, event: "UFC Fight Night" },
      { date: "2022-08-20", opponent: "José Aldo", result: "W", method: "Decision (UD)", round: 3, event: "UFC 278" },
      { date: "2021-09-25", opponent: "Marlon Moraes", result: "W", method: "TKO (punches)", round: 2, event: "UFC 266" },
      { date: "2021-05-01", opponent: "Cody Stamann", result: "W", method: "Decision (UD)", round: 3, event: "UFC on ESPN" },
    ],
    news: [
      { t: "Dvalishvili drops the bantamweight title to Yan at UFC 323", s: "ESPN", d: "2025-12-06", u: "https://www.espn.com/mma/fighter/_/id/3948572/merab-dvalishvili" },
      { t: "Yan confirms an immediate Dvalishvili rematch", s: "Yahoo Sports", d: "2026-01-20", u: "https://sports.yahoo.com/articles/petr-yan-confirms-merab-dvalishvili-182256478.html" },
      { t: "Merab Dvalishvili — record & profile", s: "Wikipedia", d: "2026-06-01", u: "https://en.wikipedia.org/wiki/Merab_Dvalishvili" },
    ],
  },
  {
    id: "ciryl-gane", name: "Ciryl Gane", nickname: "Bon Gamin", sport: "mma", flag: "🇫🇷", nationality: "France", division: "Heavyweight",
    record: { w: 14, l: 2, d: 0, nc: 1, ko: 7, sub: 3, dec: 4 }, methods: { ko: 7, sub: 3, dec: 4 }, ufcRank: 10,
    image: IMG + "5/5f/UFC_Freedom_250%2C_the_mixed_martial_arts_event_produced_by_the_Ultimate_Fighting_Championship%2C_Sunday%2C_June_14%2C_2026%2C_in_the_Grand_Foyer_of_the_White_House_-_64%28cropped%29.jpg/512px-thumbnail.jpg",
    recordUrl: "https://en.wikipedia.org/wiki/Ciryl_Gane",
    stance: "Orthodox", height: `6'4" (193 cm)`, reach: `81" (206 cm)`, age: 36, dob: "1990-04-12", hometown: "La Roche-sur-Yon, France", debut: 2018, promoterId: "ufc",
    currentTitles: ["Interim UFC Heavyweight Champion"], standing: "",
    bio: "An extraordinarily light-footed heavyweight with a Muay Thai base, 'Bon Gamin' captured the interim heavyweight title with a brutal second-round stoppage of Alex Pereira in June 2026, setting up a unification with Tom Aspinall.",
    social: { instagram: "https://instagram.com/ciryl_gane", x: "https://x.com/ciryl_gane" },
    upcoming: [{ date: "2026-09-26", opponent: "Tom Aspinall", event: "Undisputed Heavyweight (targeted)", venue: "Paris, France", title: "UFC Heavyweight" }],
    recent: [
      { date: "2026-06-14", opponent: "Alex Pereira", result: "W", method: "TKO (punches)", round: 2, event: "UFC Freedom 250 · interim HW title" },
      { date: "2025-10-25", opponent: "Tom Aspinall", result: "NC", method: "No Contest (eye poke)", round: 1, event: "UFC 321" },
      { date: "2024-12-07", opponent: "Alexander Volkov", result: "W", method: "Decision (SD)", round: 3, event: "UFC 310" },
      { date: "2023-09-02", opponent: "Serghei Spivac", result: "W", method: "TKO (punches)", round: 2, event: "UFC Fight Night 226" },
      { date: "2023-03-04", opponent: "Jon Jones", result: "L", method: "Submission (guillotine)", round: 1, event: "UFC 285 · HW title" },
      { date: "2022-09-03", opponent: "Tai Tuivasa", result: "W", method: "KO (punches)", round: 3, event: "UFC Fight Night 209" },
      { date: "2022-01-22", opponent: "Francis Ngannou", result: "L", method: "Decision (UD)", round: 5, event: "UFC 270 · HW title" },
      { date: "2021-08-07", opponent: "Derrick Lewis", result: "W", method: "TKO (punches)", round: 3, event: "UFC 265 · interim title" },
      { date: "2021-06-26", opponent: "Alexander Volkov", result: "W", method: "Decision (UD)", round: 5, event: "UFC Fight Night 190" },
      { date: "2021-02-27", opponent: "Jairzinho Rozenstruik", result: "W", method: "Decision (UD)", round: 5, event: "UFC Fight Night 186" },
    ],
    news: [
      { t: "Gane brutalizes Pereira for the interim heavyweight title", s: "CBS Sports", d: "2026-06-14", u: "https://www.cbssports.com/ufc/news/ufc-freedom-250-results-highlights-ciryl-gane-alex-pereira-knockout/" },
      { t: "Gane–Aspinall undisputed title rematch set for Paris", s: "Yahoo Sports", d: "2026-06-15", u: "https://sports.yahoo.com/mma/article/ufc-freedom-250-results-ciryl-gane-brutalizes-alex-pereira-for-interim-heavyweight-title-sets-up-tom-aspinall-rematch-041509460.html" },
      { t: "Ciryl Gane — UFC record, stats & profile", s: "CBS Sports", d: "2026-06-01", u: "https://www.cbssports.com/ufc/fighter/50035701/ciryl-gane/" },
    ],
  },
  {
    id: "joshua-van", name: "Joshua Van", nickname: "The Fearless", sport: "mma", flag: "🇲🇲", nationality: "Myanmar / USA", division: "Flyweight",
    record: { w: 17, l: 2, d: 0, ko: 6, sub: 2, dec: 9 }, methods: { ko: 6, sub: 2, dec: 9 }, ufcRank: 11,
    image: "https://www.ufc.com/images/styles/athlete_bio_full_body/s3/2026-05/VAN_JOSHUA_L_BELT_05-09.png?itok=emXQEdHo",
    recordUrl: "https://en.wikipedia.org/wiki/Joshua_Van",
    stance: "Orthodox", height: `5'6" (168 cm)`, reach: `68" (173 cm)`, age: 24, dob: "2001-09-12", hometown: "Houston, Texas, USA (born Myanmar)", debut: 2019, promoterId: "ufc",
    currentTitles: ["UFC Flyweight Champion"], standing: "",
    bio: "A high-volume pressure striker who fled Myanmar as a teenager, Van became the first UFC champion born in the 2000s. He won the flyweight title at UFC 323 and defended it by stopping Tatsuro Taira in May 2026.",
    social: { instagram: "https://instagram.com/joshua_van01", x: "https://x.com/joshuavanmma" },
    upcoming: [{ date: "2026-09-12", opponent: "Alexandre Pantoja", event: "Flyweight Title Rematch (targeted)", venue: "TBA", title: "UFC Flyweight" }],
    recent: [
      { date: "2026-05-09", opponent: "Tatsuro Taira", result: "W", method: "TKO (body kick)", round: 5, event: "UFC 328 · title defense" },
      { date: "2025-12-06", opponent: "Alexandre Pantoja", result: "W", method: "TKO (arm injury)", round: 1, event: "UFC 323 · won the title" },
      { date: "2025-06-28", opponent: "Brandon Royval", result: "W", method: "Decision (UD)", round: 3, event: "UFC 317" },
      { date: "2025-06-07", opponent: "Bruno Gustavo da Silva", result: "W", method: "TKO (punches)", round: 3, event: "UFC 316" },
      { date: "2025-03-08", opponent: "Rei Tsuruya", result: "W", method: "Decision (UD)", round: 3, event: "UFC 313" },
      { date: "2024-12-07", opponent: "Cody Durden", result: "W", method: "Decision (UD)", round: 3, event: "UFC 310" },
      { date: "2024-09-14", opponent: "Édgar Cháirez", result: "W", method: "Decision (UD)", round: 3, event: "UFC 306" },
      { date: "2024-07-13", opponent: "Charles Johnson", result: "L", method: "KO (punches)", round: 3, event: "UFC on ESPN 59" },
      { date: "2024-01-13", opponent: "Felipe Bunes", result: "W", method: "TKO (punches)", round: 2, event: "UFC Fight Night 234" },
      { date: "2023-11-11", opponent: "Kevin Borjas", result: "W", method: "Decision (UD)", round: 3, event: "UFC 295" },
    ],
    news: [
      { t: "Van stops Tatsuro Taira to defend the flyweight title at UFC 328", s: "UFC", d: "2026-05-09", u: "https://www.ufc.com/athlete/joshua-van" },
      { t: "Van wins the flyweight title after Pantoja injury at UFC 323", s: "ESPN", d: "2025-12-06", u: "https://www.espn.com/mma/story/_/id/47230871/van-wins-flyweight-title-pantoja-injures-shoulder-ufc-323" },
      { t: "Van unhappy with Pantoja as UFC 328 sets up a rematch", s: "Bloody Elbow", d: "2026-05-10", u: "https://bloodyelbow.com/2026/05/10/joshua-van-explains-why-hes-unhappy-with-alexandre-pantoja-after-ufc-328-set-up-their-rematch/" },
    ],
  },
  {
    id: "khamzat-chimaev", name: "Khamzat Chimaev", nickname: "Borz", sport: "mma", flag: "🇦🇪", nationality: "UAE (born Chechnya)", division: "Middleweight",
    record: { w: 15, l: 1, d: 0, ko: 5, sub: 6, dec: 4 }, methods: { ko: 5, sub: 6, dec: 4 }, ufcRank: 12,
    image: IMG + "b/b3/Khamzat_Chimaev_2022_%28cropped%29.png/512px-Khamzat_Chimaev_2022_%28cropped%29.png",
    recordUrl: "https://en.wikipedia.org/wiki/Khamzat_Chimaev",
    stance: "Orthodox", height: `6'2" (188 cm)`, reach: `75" (190 cm)`, age: 32, dob: "1994-05-01", hometown: "Abu Dhabi, UAE (born Gudermes, Chechnya)", debut: 2018, promoterId: "ufc",
    currentTitles: [], standing: "Former UFC Middleweight Champion",
    bio: "An overwhelming wrestler-grappler nicknamed 'The Wolf', Chimaev won the middleweight title before Sean Strickland handed him the first loss of his 16-fight career by split decision at UFC 328 in May 2026.",
    social: { instagram: "https://instagram.com/khamzat_chimaev", x: "https://x.com/khamzatchimaev" },
    upcoming: [],
    recent: [
      { date: "2026-05-09", opponent: "Sean Strickland", result: "L", method: "Decision (SD)", round: 5, event: "UFC 328 · MW title" },
      { date: "2025-08-16", opponent: "Dricus du Plessis", result: "W", method: "Decision (UD)", round: 5, event: "UFC 319 · won the title" },
      { date: "2024-10-26", opponent: "Robert Whittaker", result: "W", method: "Submission (face crank)", round: 1, event: "UFC 308" },
      { date: "2023-10-21", opponent: "Kamaru Usman", result: "W", method: "Decision (MD)", round: 3, event: "UFC 294" },
      { date: "2022-09-10", opponent: "Kevin Holland", result: "W", method: "Submission (brabo)", round: 1, event: "UFC 279" },
      { date: "2022-04-09", opponent: "Gilbert Burns", result: "W", method: "Decision (UD)", round: 3, event: "UFC 273" },
      { date: "2021-10-30", opponent: "Li Jingliang", result: "W", method: "Tech Sub (RNC)", round: 1, event: "UFC 267" },
      { date: "2020-09-19", opponent: "Gerald Meerschaert", result: "W", method: "KO (punch)", round: 1, event: "UFC Fight Night" },
      { date: "2020-07-26", opponent: "Rhys McKee", result: "W", method: "TKO (punches)", round: 1, event: "UFC on ESPN 14" },
      { date: "2020-07-16", opponent: "John Phillips", result: "W", method: "Submission (brabo)", round: 2, event: "UFC on ESPN 13" },
    ],
    news: [
      { t: "Strickland hands Chimaev his first defeat at UFC 328", s: "Al Jazeera", d: "2026-05-10", u: "https://www.aljazeera.com/sports/2026/5/10/strickland-vs-chimaev-ufc-328-strickland-downs-chimaev-on-split" },
      { t: "UFC 328: Chimaev vs Strickland — results & highlights", s: "UFC", d: "2026-05-09", u: "https://www.ufc.com/news/ufc-328-chimaev-vs-strickland-results-highlights-main-card-winners-interviews-newark" },
      { t: "Khamzat Chimaev — record and profile", s: "Wikipedia", d: "2026-06-01", u: "https://en.wikipedia.org/wiki/Khamzat_Chimaev" },
    ],
  },
  {
    id: "alexandre-pantoja", name: "Alexandre Pantoja", nickname: "The Cannibal", sport: "mma", flag: "🇧🇷", nationality: "Brazil", division: "Flyweight",
    record: { w: 30, l: 6, d: 0, ko: 11, sub: 13, dec: 6 }, methods: { ko: 11, sub: 13, dec: 6 }, ufcRank: 13,
    image: IMG + "6/62/Pantoja_2025.jpg/512px-Pantoja_2025.jpg",
    recordUrl: "https://en.wikipedia.org/wiki/Alexandre_Pantoja",
    stance: "Orthodox", height: `5'5" (165 cm)`, reach: `68" (173 cm)`, age: 36, dob: "1990-04-16", hometown: "Rio de Janeiro, Brazil", debut: 2011, promoterId: "ufc",
    currentTitles: [], standing: "Former UFC Flyweight Champion",
    bio: "A grappling-savvy veteran who holds UFC flyweight records for wins, submissions and finishes, 'The Cannibal' lost his title to Joshua Van after a freak arm injury seconds into their UFC 323 bout and is pushing for a rematch.",
    social: { instagram: "https://instagram.com/pantojamma", x: "https://x.com/pantojamma" },
    upcoming: [{ date: "2026-09-12", opponent: "Joshua Van", event: "Flyweight Title Rematch (targeted)", venue: "TBA", title: "UFC Flyweight" }],
    recent: [
      { date: "2025-12-06", opponent: "Joshua Van", result: "L", method: "TKO (arm injury)", round: 1, event: "UFC 323 · FlyW title" },
      { date: "2025-06-28", opponent: "Kai Kara-France", result: "W", method: "Submission (RNC)", round: 3, event: "UFC 317 · title defense" },
      { date: "2024-12-07", opponent: "Kai Asakura", result: "W", method: "Tech Sub (RNC)", round: 2, event: "UFC 310 · title defense" },
      { date: "2024-05-04", opponent: "Steve Erceg", result: "W", method: "Decision (UD)", round: 5, event: "UFC 301 · title defense" },
      { date: "2023-12-16", opponent: "Brandon Royval", result: "W", method: "Decision (UD)", round: 5, event: "UFC 296 · title defense" },
      { date: "2023-07-08", opponent: "Brandon Moreno", result: "W", method: "Decision (SD)", round: 5, event: "UFC 290 · won the title" },
      { date: "2022-07-30", opponent: "Alex Perez", result: "W", method: "Submission (neck crank)", round: 1, event: "UFC 277" },
      { date: "2021-08-21", opponent: "Brandon Royval", result: "W", method: "Submission (RNC)", round: 2, event: "UFC on ESPN 29" },
      { date: "2021-02-06", opponent: "Manel Kape", result: "W", method: "Decision (UD)", round: 3, event: "UFC Fight Night 184" },
      { date: "2020-07-19", opponent: "Askar Askarov", result: "L", method: "Decision (UD)", round: 3, event: "UFC Fight Night 172" },
    ],
    news: [
      { t: "Pantoja loses the flyweight title to Van after a freak injury", s: "ESPN", d: "2025-12-06", u: "https://www.espn.com/mma/fighter/_/id/2560746/alexandre-pantoja" },
      { t: "What's next for former champ Alexandre Pantoja", s: "Sherdog", d: "2026-05-15", u: "https://www.sherdog.com/fighter/Alexandre-Pantoja-25023" },
      { t: "Alexandre Pantoja — UFC fight history", s: "ESPN", d: "2026-06-01", u: "https://www.espn.com/mma/fighter/history/_/id/2560746/alexandre-pantoja" },
    ],
  },
  {
    id: "arman-tsarukyan", name: "Arman Tsarukyan", nickname: "Akhalkalakets", sport: "mma", flag: "🇦🇲", nationality: "Armenia", division: "Lightweight",
    record: { w: 23, l: 3, d: 0, ko: 6, sub: 7, dec: 10 }, methods: { ko: 6, sub: 7, dec: 10 }, ufcRank: 14,
    image: IMG + "b/b9/Arman_Tsarukyan_2019.jpg/512px-Arman_Tsarukyan_2019.jpg",
    recordUrl: "https://en.wikipedia.org/wiki/Arman_Tsarukyan",
    stance: "Orthodox", height: `5'7" (170 cm)`, reach: `72" (183 cm)`, age: 29, dob: "1996-10-11", hometown: "Yerevan, Armenia", debut: 2017, promoterId: "ufc",
    currentTitles: [], standing: "Top Lightweight Contender",
    bio: "A complete mixed martial artist with elite wrestling and underrated power, Tsarukyan is the No. 1-ranked lightweight contender and has stayed busy across grappling and MMA while awaiting his shot at the title.",
    social: { instagram: "https://instagram.com/armantsarukyanofficial", x: "https://x.com/arm_official01" },
    upcoming: [{ date: "2026-10-17", opponent: "TBA", event: "UFC Lightweight Title Eliminator (targeted)", venue: "TBA", title: "UFC Lightweight" }],
    recent: [
      { date: "2025-11-22", opponent: "Dan Hooker", result: "W", method: "Submission (arm-triangle)", round: 2, event: "UFC Fight Night" },
      { date: "2024-04-13", opponent: "Charles Oliveira", result: "W", method: "Decision (SD)", round: 3, event: "UFC 300" },
      { date: "2023-12-02", opponent: "Beneil Dariush", result: "W", method: "KO (knee & punches)", round: 1, event: "UFC on ESPN" },
      { date: "2023-06-17", opponent: "Joaquim Silva", result: "W", method: "TKO (punches)", round: 3, event: "UFC on ESPN" },
      { date: "2022-12-17", opponent: "Damir Ismagulov", result: "W", method: "Decision (UD)", round: 3, event: "UFC Fight Night" },
      { date: "2022-06-25", opponent: "Mateusz Gamrot", result: "L", method: "Decision (UD)", round: 5, event: "UFC on ESPN" },
      { date: "2022-02-26", opponent: "Joel Álvarez", result: "W", method: "TKO (punches)", round: 2, event: "UFC Fight Night" },
      { date: "2021-09-18", opponent: "Christos Giagos", result: "W", method: "TKO (punches)", round: 1, event: "UFC Fight Night" },
      { date: "2021-01-24", opponent: "Matt Frevola", result: "W", method: "Decision (UD)", round: 3, event: "UFC 257" },
      { date: "2020-07-18", opponent: "Davi Ramos", result: "W", method: "Decision (UD)", round: 3, event: "UFC Fight Night" },
    ],
    news: [
      { t: "Tsarukyan stays unbeaten in 2026 and eyes a title shot", s: "ESPN", d: "2026-06-01", u: "https://www.espn.com/mma/fighter/_/id/4419372/arman-tsarukyan" },
      { t: "Arman Tsarukyan — record, next fight & stats", s: "Sherdog", d: "2026-06-10", u: "https://www.sherdog.com/fighter/Arman-Tsarukyan-213913" },
      { t: "Arman Tsarukyan — career profile", s: "Wikipedia", d: "2026-06-01", u: "https://en.wikipedia.org/wiki/Arman_Tsarukyan" },
    ],
  },
  {
    id: "charles-oliveira", name: "Charles Oliveira", nickname: "do Bronx", sport: "mma", flag: "🇧🇷", nationality: "Brazil", division: "Lightweight",
    record: { w: 36, l: 11, d: 0, nc: 1, ko: 11, sub: 17, dec: 8 }, methods: { ko: 11, sub: 17, dec: 8 }, ufcRank: 15,
    image: IMG + "3/3e/Charles_Oliveira_do_Bronxs.jpg/512px-Charles_Oliveira_do_Bronxs.jpg",
    recordUrl: "https://en.wikipedia.org/wiki/Charles_Oliveira",
    stance: "Orthodox", height: `5'10" (178 cm)`, reach: `74" (188 cm)`, age: 36, dob: "1989-10-17", hometown: "Guarujá, São Paulo, Brazil", debut: 2008, promoterId: "ufc",
    currentTitles: ["UFC 'BMF' Championship"], standing: "Former UFC Lightweight Champion",
    bio: "The UFC's all-time leader in finishes and submissions, 'do Bronx' is a beloved warrior who claimed the symbolic 'BMF' title with a decision win over Max Holloway in March 2026.",
    social: { instagram: "https://instagram.com/charlesdobronxs", x: "https://x.com/charlesdobronxs" },
    upcoming: [],
    recent: [
      { date: "2026-03-07", opponent: "Max Holloway", result: "W", method: "Decision (UD)", round: 5, event: "UFC 326 · 'BMF' title" },
      { date: "2025-10-11", opponent: "Mateusz Gamrot", result: "W", method: "Submission (face crank)", round: 2, event: "UFC Fight Night 261" },
      { date: "2025-06-28", opponent: "Ilia Topuria", result: "L", method: "KO (punches)", round: 1, event: "UFC 317 · vacant LW title" },
      { date: "2024-11-16", opponent: "Michael Chandler", result: "W", method: "Decision (UD)", round: 5, event: "UFC 309" },
      { date: "2024-04-13", opponent: "Arman Tsarukyan", result: "L", method: "Decision (SD)", round: 3, event: "UFC 300" },
      { date: "2023-06-10", opponent: "Beneil Dariush", result: "W", method: "TKO (punches)", round: 1, event: "UFC 289" },
      { date: "2022-10-22", opponent: "Islam Makhachev", result: "L", method: "Submission (arm-triangle)", round: 2, event: "UFC 280 · LW title" },
      { date: "2022-05-07", opponent: "Justin Gaethje", result: "W", method: "Submission (RNC)", round: 1, event: "UFC 274" },
      { date: "2021-12-11", opponent: "Dustin Poirier", result: "W", method: "Submission (RNC)", round: 3, event: "UFC 269 · title defense" },
      { date: "2021-05-15", opponent: "Michael Chandler", result: "W", method: "TKO (punches)", round: 2, event: "UFC 262 · won the title" },
    ],
    news: [
      { t: "Oliveira outpoints Holloway to win the 'BMF' title at UFC 326", s: "ESPN", d: "2026-03-07", u: "https://www.espn.com/mma/fighter/_/id/2504169/charles-oliveira" },
      { t: "What's next for Charles Oliveira?", s: "Yardbarker", d: "2026-04-01", u: "https://www.yardbarker.com/mma/articles/whats_next_for_charles_oliveira/s1_17349_42398857" },
      { t: "Charles Oliveira — record & profile", s: "Wikipedia", d: "2026-06-01", u: "https://en.wikipedia.org/wiki/Charles_Oliveira" },
    ],
  },
];

/* Expose for the app (works via plain <script> include, no modules needed). */
window.FIGHTERS = FIGHTERS;
window.PROMOTERS = PROMOTERS;
